objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Building</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/searchBuildingController.cls
public class searchBuildingController {
    @AuraEnabled
 public static List < Building__c > fetchBuilding (String searchKeyWord) {
  String searchKey = '%'+searchKeyWord+'%';
 
  string lstOfBuilding = '';
          if(searchKeyWord!=null){
            lstOfBuilding = 'select id, Name, Area__c, City__c, Owner_Name__c, Phone__c from Building__c where Name LIKE: searchKey ';
        }else{
            lstOfBuilding = 'select id, Name, Area__c, City__c, Owner_Name__c, Phone__c from Building__c ';
        }                        
             
   list<sobject> sobjectlist = database.query(lstOfBuilding);
        return sobjectlist;
  
 }
    
}