objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <label>Annual Income</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assets_Value__c</fullName>
        <label>Assets Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Caste__c</fullName>
        <label>Caste</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Religion__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OC</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>SC</fullName>
                </value>
                <value>
                    <fullName>ST</fullName>
                </value>
                <value>
                    <fullName>Inter-Caste</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Bith__c</fullName>
        <label>Date of Bith</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Drinking_Habit__c</fullName>
        <label>Drinking Habit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regular Drinker</fullName>
                </value>
                <value>
                    <fullName>Occasional Drinker</fullName>
                </value>
                <value>
                    <fullName>Never Drinks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eating_habit__c</fullName>
        <label>Eating habit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vegetarian</fullName>
                </value>
                <value>
                    <fullName>Eggetarian</fullName>
                </value>
                <value>
                    <fullName>Non-Vegetarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10+2</fullName>
                </value>
                <value>
                    <fullName>10th</fullName>
                </value>
                <value>
                    <fullName>B.Com</fullName>
                </value>
                <value>
                    <fullName>B.Science</fullName>
                </value>
                <value>
                    <fullName>B.Tech</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BBA</fullName>
                </value>
                <value>
                    <fullName>BED</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>LLB</fullName>
                </value>
                <value>
                    <fullName>LLM</fullName>
                </value>
                <value>
                    <fullName>M.Tech</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MBA</fullName>
                </value>
                <value>
                    <fullName>MCA</fullName>
                </value>
                <value>
                    <fullName>MSC</fullName>
                </value>
                <value>
                    <fullName>PhD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Languages_Known__c</fullName>
        <label>Languages Known</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Bengali</fullName>
                </value>
                <value>
                    <fullName>Telugu</fullName>
                </value>
                <value>
                    <fullName>Marathi</fullName>
                </value>
                <value>
                    <fullName>Tamil</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Kannada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Guntur</fullName>
                </value>
                <value>
                    <fullName>Vijayawada</fullName>
                </value>
                <value>
                    <fullName>Warangal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MailID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>MailID</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Mother_Tongue__c</fullName>
        <label>Mother Tongue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Telugu</fullName>
                </value>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>Urdu</fullName>
                </value>
                <value>
                    <fullName>Bengali</fullName>
                </value>
                <value>
                    <fullName>Gujarati</fullName>
                </value>
                <value>
                    <fullName>Kannada</fullName>
                </value>
                <value>
                    <fullName>Malayalam</fullName>
                </value>
                <value>
                    <fullName>Marathi</fullName>
                </value>
                <value>
                    <fullName>Marwari</fullName>
                </value>
                <value>
                    <fullName>Oriya</fullName>
                </value>
                <value>
                    <fullName>Punjabi</fullName>
                </value>
                <value>
                    <fullName>Sindhi</fullName>
                </value>
                <value>
                    <fullName>Tamil</fullName>
                </value>
                <value>
                    <fullName>Arunachali</fullName>
                </value>
                <value>
                    <fullName>Assamese</fullName>
                </value>
                <value>
                    <fullName>Awadhi</fullName>
                </value>
                <value>
                    <fullName>Bihari</fullName>
                </value>
                <value>
                    <fullName>Chatisgarhi</fullName>
                </value>
                <value>
                    <fullName>Dogri</fullName>
                </value>
                <value>
                    <fullName>Miji</fullName>
                </value>
                <value>
                    <fullName>Mizo</fullName>
                </value>
                <value>
                    <fullName>Monpa</fullName>
                </value>
                <value>
                    <fullName>Nicobarese</fullName>
                </value>
                <value>
                    <fullName>Nepali</fullName>
                </value>
                <value>
                    <fullName>Rajasthani</fullName>
                </value>
                <value>
                    <fullName>Sanskrit</fullName>
                </value>
                <value>
                    <fullName>Santhali</fullName>
                </value>
                <value>
                    <fullName>Sourashtra</fullName>
                </value>
                <value>
                    <fullName>Tripuri</fullName>
                </value>
                <value>
                    <fullName>Tulu</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Private Employee</fullName>
                </value>
                <value>
                    <fullName>Govt Employee</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Daily Wager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>8</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Photo__c</fullName>
        <label>Photo</label>
        <length>1000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Religion__c</fullName>
        <label>Religion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hindu</fullName>
                </value>
                <value>
                    <fullName>Muslim</fullName>
                </value>
                <value>
                    <fullName>Christian</fullName>
                </value>
                <value>
                    <fullName>Inter Religion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Smoking__c</fullName>
        <label>Smoking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Smoker</fullName>
                </value>
                <value>
                    <fullName>Non-Smoker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/pppppppp.cls
public class pppppppp {
      public List<Profile__c> profiles{get;set;}
      public List<Profile__c> Login_User{get;set;}
      public String profile_Id{set;get;}
      Public string photo_url {get;set;}
      public boolean Show_profile{get;set;}
   	  public profile__c user_Obj{get; set;}
      public boolean Apex_message{get;set;}
      public integer Photo_Index{get;set;} 
      public List<profile_display> profiledisplayList{get;set;}
      public boolean Logindetails{get;set;}
      public boolean UserDetails{get;set;}
      public boolean Registrationform{get;set;}
      public boolean ProfileDetails{get;set;}  
      public boolean ViewRecords{get;set;}   
      public String ids{get;set;}
 	  public boolean Search_Display{get;set;}     
      public boolean search_Details{get;set;}
      public boolean Profile_Information{get;set;}
      public List<profile_display> SearchList{get;set;}
      public Profile__c Profile_Search{get;set;}
 																/*constructor*/
  public pppppppp()
	{
        Search_Display=True;
        search_Details=True;
    }
																    
    public void Filtered_Search()
    { 	
        search_Details=False;
        Search_Display=true;
    
        system.debug('user_Obj.Religion__c'+user_Obj.Religion__c);
        system.debug('user_Obj.Occupation__c'+user_Obj.Occupation__c);
        system.debug('user_Obj.Location__c'+user_Obj.Location__c);
        system.debug(' profiledisplayList'+ profiledisplayList);
        SearchList=new List<profile_display>(); 
        for(profile_display profile_D:profiledisplayList){
            if(profile_D.Occupation==user_Obj.Occupation__c && profile_D.Religion==user_Obj.Religion__c && profile_D.Location == user_Obj.Location__c )
            {
                system.debug('Welcome to sublist');
                SearchList.add(profile_D);
            }
        }
        system.debug('Welcome to sublist'+SearchList);
       
    } 
    /*View Profile*/ 
     public void View_Profile(){
        Profile_Search=new Profile__c();
        ProfileDetails=False;
        Registrationform=False;
        Logindetails=False;
        UserDetails=False;
        search_Details=False;
        Search_Display=False;
        Profile_Information=True;
        system.debug('View_Profile'+profile_Id);
         for(Profile__c profile_Search_data:profiles ){
             if(profile_Search_data.id==profile_Id){
                 system.debug('profile_Search_data'+profile_Search_data);
                 Profile_Search=profile_Search_data;
             }
         }
         system.debug('profile_Search'+ Profile_Search);
       /* user_Obj=[select id,Name,MailID__c,Password__c,Gender__c,Religion__c,Caste__c,Mother_Tongue__c,Phone__c,Date_of_Bith__c,
             Height__c,Education__c,Occupation__c,Annual_Income__c,Location__c,Assets_Value__c,Eating_habit__c,
             Drinking_Habit__c,Smoking__c,Address__c,Languages_Known__c,Photo__c from Profile__c where id=:profile_Id];*/
        system.debug(profile_Id);
    }

       /*wrapper class*/ 
  public class profile_display{
        Public String Photo{get;set;}
        public String Name{get;set;}
        public String Occupation {get;set;}
        public String Location {get;set;}
        public String Religion {get;set;}
        public String id {get;set;}
    }  
}