objects/Phone__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Date_of_Purchase__c</fullName>
        <label>Date of Purchase</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_No__c</fullName>
        <label>Phone No</label>
        <type>Phone</type>
    </fields>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/datatabledisplay.cls
public class datatabledisplay {
    @AuraEnabled
    public static list<sObject> Records (string objects){
        string Query;
        if(objects=='Phone__c'){
        Query='select Id,Name,Owner_Name__c,Phone_No__c,Date_of_Purchase__c,Address__c from '+objects;
        }else{
            Query='select Id,name,Owner_Name__c,Phone_No__c,Date_of_Purchase__c,Address__c,Store__c from '+objects;    
        }
        List<Sobject> sobjectlist= database.query(Query);
        system.debug('sobjectlist'+sobjectlist);
        return sobjectlist;
    }
}