objects/Phone__c.object
<CustomObject>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContactListController.cls
public class ContactListController{

    public  id tid{get;set;}
    public ContactListController(ApexPages.StandardController controller)
     {
          Profile__c rec= (Profile__c)controller.getRecord();
          if(rec !=null)        
             tid = rec.id;
           System.debug('**************Verify Id is here**************'+tid); 
     }
     
    public List<Profile__c> getMydtpList()
    {
         List<Profile__c> mydtpList =[select Name, Phone__c from Profile__c ];
        return mydtpList ;
        }
}